### ISSUE TITLE
conflict with "stable-diffusion-webui-depthmap-script" extention?

### ISSUE THREAD

**Issue by jasoncow007** [cheald/sd-webui-loractl#10]
*** Error loading script: depthmap.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 8, in <module>
        from src import common_ui
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py", line 6, in <module>
        from src import backbone, video_mode
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\video_mode.py", line 8, in <module>
        from src import core
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 26, in <module>
        from src.depthmap_generation import ModelHolder
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 21, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: depthmap_api.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_api.py", line 15, in <module>
        from src.core import core_generation_funnel
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 26, in <module>
        from src.depthmap_generation import ModelHolder
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 21, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: normalmap.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-normalmap-script\scripts\normalmap.py", line 35, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by jasoncow007** [comment]
when disable "stable-diffusion-webui-depthmap-script" in launcher , error will be like this:

*** Error loading script: loractl.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\scripts\loractl.py", line 5, in <module>
        from lib import utils, plot, lora_ctl_network, network_patch
      File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\lib\plot.py", line 6, in <module>
        from lib.lora_ctl_network import networks
      File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\lib\lora_ctl_network.py", line 10, in <module>
        import network, networks, network_lora, extra_networks_lora
    ModuleNotFoundError: No module named 'network'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
sd-webui-prompt-all-in-one background API service started successfully.
2023-08-09 21:55:46,903 - roop - INFO - roop v0.0.2
2023-08-09 21:55:46,908 - roop - INFO - roop v0.0.2
*** Error loading script: normalmap.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\stable-diffusion-webui-normalmap-script\scripts\normalmap.py", line 35, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by cheald** [comment]
This extension only supports 1.5.0 or later.

**Comment by jasoncow007** [comment]
change to SD 1.5,and I did't enable the extention, then error occurs as bellw,,,,is this another conflict?

Speed: 2.0ms preprocess, 16.5ms inference, 3.3ms postprocess per image at shape (1, 3, 640, 448)
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000016D01ACABC0>, <modules.extra_networks.ExtraNetworkParams object at 0x0000016D01ACB5E0>]: ValueError
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\loractl\lib\lora_ctl_network.py", line 27, in activate
    lora_weights[name] = utils.params_to_weights(params)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\loractl\lib\utils.py", line 43, in params_to_weights
    weights["te"] = sorted_positions(params.positional[1])
  File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\loractl\lib\utils.py", line 8, in sorted_positions
    steps = [[float(s.strip()) for s in x.split("@")]
  File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\loractl\lib\utils.py", line 8, in <listcomp>
    steps = [[float(s.strip()) for s in x.split("@")]
  File "D:\sd-webui-aki-v4\extensions\sd-webui-loractl\loractl\lib\utils.py", line 8, in <listcomp>
    steps = [[float(s.strip()) for s in x.split("@")]
ValueError: could not convert string to float: '1.4)'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by cheald** [comment]
That's a very curious one. I don't know why python wouldn't be able to cast "1.4" as a float. Do you have locale settings which don't use decimals for fractional numbers, or something along those lines?
