### ISSUE TITLE
Error loading script: loractl.py

### ISSUE THREAD

**Issue by Tr4p-kun** [cheald/sd-webui-loractl#13]
```
*** Error loading script: loractl.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-directml\modules\scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui-directml\extensions\sd-webui-loractl\scripts\loractl.py", line 5, in <module>
        from loractl.lib import utils, plot, lora_ctl_network, network_patch
      File "D:\stable-diffusion-webui-directml\extensions\sd-webui-loractl\loractl\lib\plot.py", line 6, in <module>
        from loractl.lib.lora_ctl_network import networks
      File "D:\stable-diffusion-webui-directml\extensions\sd-webui-loractl\loractl\lib\lora_ctl_network.py", line 10, in <module>
        import network, networks, network_lora, extra_networks_lora
      File "D:\stable-diffusion-webui-directml\extensions-builtin\Lora\networks.py", line 463, in <module>
        list_available_networks()
      File "D:\stable-diffusion-webui-directml\extensions-builtin\Lora\networks.py", line 402, in list_available_networks
        candidates += list(shared.walk_files(shared.cmd_opts.lyco_dir_backcompat, allowed_extensions=[".pt", ".ckpt", ".safetensors"]))
    AttributeError: 'Namespace' object has no attribute 'lyco_dir_backcompat'
 ```

everytime  i start up my stable-diffusion-webui this comes did i do something wrong here?

**Comment by cheald** [comment]
What version of the webui are you using (version, and git hash via `git rev-parse HEAD`)? This looks like an error originating from webui itself. I need more information to track it down.

**Comment by Tr4p-kun** [comment]
im using (https://github.com/lshqqytiger/stable-diffusion-webui-directml) on the version 1.5.0 (with python  3.10.6) and the hash of git is 066f3bbc7056a7d55a7224b67f3d9c5610304191

**Comment by cheald** [comment]
I can't replicate this with a fresh clone of that repository. The extension loads and works fine here with commit 066f3bbc7056a7d55a7224b67f3d9c5610304191 and 58b9fb5f1db36ea8335b7553b5391e4ec1e53393 (HEAD as of this comment).

**Comment by cheald** [comment]
Closing this one pending further information. Please reopen if you have a replication procedure.
