### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [cheald/sd-webui-loractl#17]
use A1111`s webui latest dev 9d2299ed0bd6c81cae8a7ba4ca22d6a14fb27bef

after 9b19512dd60861352b4a469a5d221354082f7243 cause error

```
activating extra network lora: NameError
Traceback (most recent call last):
  File "J:\SDWebUI\modules\extra_networks.py", line 116, in activate
    extra_network.activate(p, [])
  File "J:\SDWebUI\extensions\sd-webui-loractl\loractl\lib\lora_ctl_network.py", line 24, in activate
    if not utils.is_active():
           ^^^^^^^^^^^^^^^^^
  File "J:\SDWebUI\extensions\sd-webui-loractl\loractl\lib\utils.py", line 92, in is_active
    return loractl_active
           ^^^^^^^^^^^^^^
NameError: name 'loractl_active' is not defined
```

**Comment by cheald** [comment]
Whoops, thanks. Fixed.
