### ISSUE TITLE
Float issue

### ISSUE THREAD

**Issue by sadsilly** [cheald/sd-webui-loractl#19]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E3303518D0>]: ValueError
Traceback (most recent call last):
  File "C:\ai\final sd\stable-diffusion-webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\ai\final sd\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 30, in activate
    te_multiplier = float(params.positional[1]) if len(params.positional) > 1 else 1.0
ValueError: could not convert string to float: '0@0,0.4@0.5'

started getting this after updating to 1.6
![image](https://github.com/cheald/sd-webui-loractl/assets/37007483/40e4c93d-1586-495f-8d6f-e7c5684ee881)

**Comment by sadsilly** [comment]
i just noticed it also giving me this error when i launch automatic

![image](https://github.com/cheald/sd-webui-loractl/assets/37007483/36bbeee4-d330-457c-92b0-aaf82f52bb5f)

**Comment by sadsilly** [comment]
i tried close bracketing that line now i am getting 
![image](https://github.com/cheald/sd-webui-loractl/assets/37007483/e855547b-503e-458a-86d5-6dcc3f84e798)

**Comment by sadsilly** [comment]
i reinstall SD now working so do not worry about it. i do not know what was wrong other one. :D

**Comment by sadsilly** [comment]
So..... i have bad news i broke it again Q_Q! 
![image](https://github.com/cheald/sd-webui-loractl/assets/37007483/6f14215f-72ab-4c8e-8eab-3e27fb90d8fe)

sd hard crash one prompt an now i think it stuck in a state where it wont activate.

**Comment by sadsilly** [comment]
so... i found indirect work around to solve this problem. i just deleted the extension closed terminal restarted it then reinstall it an now it works 
?___?

**Comment by sadsilly** [comment]
to give you update. turn out i was just writing them wrong it causing errors so you can delete this. sorry wasting everyone time D:!
