### ISSUE TITLE
No module named 'network'  ?

### ISSUE THREAD

**Issue by IcyLucario** [cheald/sd-webui-loractl#26]
```
Restarting UI...
Error loading script: loractl.py
Traceback (most recent call last):
  File "D:\delme\AIStuff\stable-diffusion-webui\models\Stable-diffusion\webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\delme\AIStuff\stable-diffusion-webui\models\Stable-diffusion\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\delme\AIStuff\stable-diffusion-webui\models\Stable-diffusion\webui\extensions\sd-webui-loractl\scripts\loractl.py", line 5, in <module>
    from loractl.lib import utils, plot, lora_ctl_network, network_patch
  File "D:\delme\AIStuff\stable-diffusion-webui\models\Stable-diffusion\webui\extensions\sd-webui-loractl\loractl\lib\plot.py", line 6, in <module>
    from loractl.lib.lora_ctl_network import networks
  File "D:\delme\AIStuff\stable-diffusion-webui\models\Stable-diffusion\webui\extensions\sd-webui-loractl\loractl\lib\lora_ctl_network.py", line 10, in <module>
    import network, networks, network_lora, extra_networks_lora
ModuleNotFoundError: No module named 'network'
```

Any idea how to fix this?

**Comment by IcyLucario** [comment]
Updating did not help, but a clean re-install fixed issues I had. Oh well, update SD people!
